# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget
from secondPage import Ui_MainWindow2


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1151, 839)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1153, 851))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.label.setFocusPolicy(QtCore.Qt.StrongFocus)

        frame_geometry = MainWindow.frameGeometry()
        center_point = QDesktopWidget().availableGeometry().center()
        frame_geometry.moveCenter(center_point)
        MainWindow.move(frame_geometry.topLeft())

        self.label.setStyleSheet("\n"
"border-image: url(:/newPrefix/Screenshot_2023-06-12_13-32-58.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(250, 730, 631, 51))
        self.textEdit.setFocusPolicy(QtCore.Qt.TabFocus)
        self.textEdit.setAutoFillBackground(False)
        self.textEdit.setStyleSheet("background-image: url(:/newPrefix/Screenshot_2023-06-12_13-32-58.png);\n"
"font: 75 15pt \"Latin Modern Mono Light Cond\";")
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.textEdit.setObjectName("textEdit")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(1010, 380, 91, 31))
        self.toolButton.setStyleSheet("background-image: url(:/newPrefix/Screenshot_2023-06-12_13-32-58.png);\n"
"color: rgb(26, 95, 180);")
        self.toolButton.setObjectName("toolButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
        self.toolButton.clicked.connect(self.nextbut)
    def nextbut(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()
        MainWindow.close()


#
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZANY ANTIVIRUS"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Latin Modern Mono Light Cond\'; font-size:15pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:26pt; font-weight:600;\">ZANY</span><span style=\" font-size:20pt;\"> Antivirus Ugulamasına Hoşgelidiniz</span></p></body></html>"))
        self.toolButton.setText(_translate("MainWindow", "NEXT =>"))
import firstsorce

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
