# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secenek.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QDesktopWidget
#from secondPage import Ui_MainWindow2
from secondmalware import Ui_MainWindow3
from firstmalware import Ui_Dialog


class Ui_MainWindow0(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1149, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1151, 781))

        frame_geometry = MainWindow.frameGeometry()
        center_point = QDesktopWidget().availableGeometry().center()
        frame_geometry.moveCenter(center_point)
        MainWindow.move(frame_geometry.topLeft())

        self.label.setStyleSheet("background-image: url(:/newPrefix/Screenshot_2023-06-12_13-32-58.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(900, 170, 151, 61))
        self.toolButton.setStyleSheet("background-image: url(:/newPrefix/Screenshot_2023-06-12_13-32-58.png);")
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(900, 90, 151, 61))
        self.toolButton_2.setStyleSheet("background-image: url(:/newPrefix/Screenshot_2023-06-12_13-32-58.png);")
        self.toolButton_2.setObjectName("toolButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 700, 201, 41))
        self.pushButton.setStyleSheet("background-image: url(:/newPrefix/Screenshot_2023-06-12_13-32-58.png);")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.geriDon)
        self.toolButton_2.clicked.connect(self.scanc)
        self.toolButton.clicked.connect(self.fscanc)
    def geriDon(self):
        pass       

    def fscanc(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()
    
    def scanc(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow3()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZANY ANTIVIRUS"))
        self.toolButton.setText(_translate("MainWindow", "FSCAN"))
        self.toolButton_2.setText(_translate("MainWindow", "SCAN"))
        self.pushButton.setText(_translate("MainWindow", "Bilgilendirmeye Dön"))
import secenek

def openwindow():
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow0()
        ui.setupUi(MainWindow)
        MainWindow.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow0()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
