# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget
from secenekeler import Ui_MainWindow0

class Ui_MainWindow2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1151, 839)
        MainWindow.setAutoFillBackground(False)
        

        frame_geometry = MainWindow.frameGeometry()
        center_point = QDesktopWidget().availableGeometry().center()
        frame_geometry.moveCenter(center_point)
        MainWindow.move(frame_geometry.topLeft())
    

        MainWindow.setStyleSheet("background-image: url(:/newPrefix/Screenshot_2023-06-12_13-32-58.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 20, 1051, 91))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(50, 660, 1061, 131))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1040, 380, 87, 27))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.nextbut)
        

    def nextbut(self):
        self.MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow0()
        self.ui.setupUi(self.MainWindow)
        self.MainWindow.show()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZANY ANTIVIRUS"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; text-decoration: underline;\">Burası uygulamaya başlamadan önceki son aşamadır, bilgilendirme amaçlıdır.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Karşınıza iki seçenek çıkacaktır. Bunlardan birincisi </span><span style=\" font-size:18pt; color:#1a5fb4;\">FSCAN </span><span style=\" font-size:18pt; color:#ffffff;\">ikinci ise </span><span style=\" font-size:18pt; color:#1a5fb4;\">SCAN </span><span style=\" font-size:18pt; color:#ffffff;\">olarak adlandırılmıştır. </span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cantarell\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#1a5fb4;\">FSCAN</span><span style=\" font-size:16pt;\"> butonuna basmanız durumunda bir dosya yolu girmeniz beklenmektedir. Verdiğiniz konumdaki dosya üzerinde, bir sonraki sayfada seçeceğiniz zararlı yazılım türlerinden biri için tarama yapılacaktır.</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#1a5fb4;\">SCAN</span><span style=\" font-size:16pt;\"> butonuna basarsanız, yine bir sonraki sayfada seçeceğiniz zararlı yazılım çeşitlerinden birine göre tarama yapılacaktı </span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "NEXT =>"))


import secondSorce


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
